package com.example.consume.soap.stub;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.2 2025-12-15T19:28:01.419+01:00
 * Generated source version: 3.6.2
 *
 */
@WebService(targetNamespace = "http://www.example.com/soap/ws/loanEligibility", name = "LoanEligibilityPort")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LoanEligibilityPort {

	@WebMethod(operationName = "Customer")
	@Oneway
	public void customer(

			@WebParam(partName = "CustomerRequest", name = "CustomerRequest", targetNamespace = "http://www.example.com/soap/ws/loanEligibility") CustomerRequest customerRequest);
}
