package com.example.consume.soap.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.2 2025-12-15T19:28:01.453+01:00
 * Generated source version: 3.6.2
 *
 */
@WebServiceClient(name = "LoanEligibilityPortService", wsdlLocation = "file:/C:/Users/SBS/eclipse-workspace/spring-boot-soap-ws-client1/src/main/resources/wsdl/loanEligibility.wsdl", targetNamespace = "http://www.example.com/soap/ws/loanEligibility")
public class LoanEligibilityPortService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://www.example.com/soap/ws/loanEligibility",
			"LoanEligibilityPortService");
	public final static QName LoanEligibilityPortSoap11 = new QName("http://www.example.com/soap/ws/loanEligibility",
			"LoanEligibilityPortSoap11");
	static {
		URL url = null;
		try {
			url = new URL(
					"file:/C:/Users/SBS/eclipse-workspace/spring-boot-soap-ws-client1/src/main/resources/wsdl/loanEligibility.wsdl");
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(LoanEligibilityPortService.class.getName()).log(
					java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
					"file:/C:/Users/SBS/eclipse-workspace/spring-boot-soap-ws-client1/src/main/resources/wsdl/loanEligibility.wsdl");
		}
		WSDL_LOCATION = url;
	}

	public LoanEligibilityPortService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public LoanEligibilityPortService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public LoanEligibilityPortService() {
		super(WSDL_LOCATION, SERVICE);
	}

	public LoanEligibilityPortService(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	public LoanEligibilityPortService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	public LoanEligibilityPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return returns LoanEligibilityPort
	 */
	@WebEndpoint(name = "LoanEligibilityPortSoap11")
	public LoanEligibilityPort getLoanEligibilityPortSoap11() {
		return super.getPort(LoanEligibilityPortSoap11, LoanEligibilityPort.class);
	}

	/**
	 *
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *                 on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns LoanEligibilityPort
	 */
	@WebEndpoint(name = "LoanEligibilityPortSoap11")
	public LoanEligibilityPort getLoanEligibilityPortSoap11(WebServiceFeature... features) {
		return super.getPort(LoanEligibilityPortSoap11, LoanEligibilityPort.class, features);
	}

}
